name: node-exporter
title: Node exporter
type: infrastructure
icon: prometheus
scalable: false
helm:
  name: prometheus-community
  source: https://prometheus-community.github.io/helm-charts
  chart: prometheus-community/prometheus-node-exporter
  version: 4.52.2

workloads:
- name: main
  selector:
    matchLabels:
      app.kubernetes.io/instance: '{{helm.release}}'
  kind: daemonset
  primary: true
  helm:
    labels: podLabels
    annotations: daemonsetAnnotations
    volumes: extraVolumes
  containers:
  - name: node-exporter
    helm:
      resources: resources
      envKV: env
      mounts: extraVolumeMounts
