name: node-exporter
title: Node exporter
type: infrastructure
icon: prometheus
scalable: false
containers:
  - name: node-exporter

helm:
  name: prometheus-community
  source: https://prometheus-community.github.io/helm-charts
  chart: prometheus-community/prometheus-node-exporter
  version: 4.52.2
  configurations:
  - container: node-exporter
    labels: podLabels
    annotations: daemonsetAnnotations
    resources: resources
    env: env
    volumes: extraVolumes
    mounts: extraVolumeMounts 
