apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: wodby/monitoring-agent:0.1.0-rc.6
          imagePullPolicy: IfNotPresent
          args:
            - node-exporter
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 80
              name: http-metrics
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: [ "SYS_TIME" ]
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: rootfs
              mountPath: /host/root
              readOnly: true
            - name: sysfs
              mountPath: /host/sys
              readOnly: true
            - name: procfs
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: sysfs
          hostPath:
            path: /sys
        - name: procfs
          hostPath:
            path: /proc
